### ISSUE TITLE
outputModuleName can only have a single level (only one dot `.`)

### ISSUE THREAD

**Issue by jonathanjouty** [ChristophP/parcel-transformer-elm-svg-modules#3]
Setting `outputModuleName` to `Acme.Icons` works, but if you set it to `Acme.Factory.Icons` then you end up with a file named `Factory.Icons.elm`

I believe all that is required is adding the [`g` (global) option](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#description) to `.replace` in https://github.com/ChristophP/parcel-transformer-elm-svg-modules/blob/main/src/ElmSvgModulesTransformer.js#L29

I can make a PR if this sounds acceptable?
Thank you for creating and maintaining this package!

**Comment by ChristophP** [comment]
Hey @jonathanjouty ,

glad this package is of use to you.

Yes, you're proposed solution sounds good enough to me. A PR would be appreciated.
