### ISSUE TITLE
Possible race condition when running over multiple sources

### ISSUE THREAD

**Issue by Janiczek** [ChristophP/parcel-transformer-elm-svg-modules#5]
Hello!
We're using this package at work and have recently started seeing issues with CI failing (Elm compiler seeing truncated cache files):

```
Compilation failed
+-------------------------------------------------------------------------------
|  Corrupt File: /home/runner/work/frontend-gcp/frontend-gcp/elm/elm-stuff/0.19.1/i.dat
|   Byte Offset: 1183122
|       Message: not enough bytes
|
| Please report this to https://github.com/elm/compiler/issues
| Trying to continue anyway.
+-------------------------------------------------------------------------------
{"type":"error","path":null,"title":"CORRUPT CACHE","message":["It looks like some of the information cached in elm-stuff/ has been corrupted.\nTry deleting your elm-stuff/ directory to get unstuck.\n\n",{"bold":false,"underline":true,"color":null,"string":"Note"},": This almost certainly means that a 3rd party tool (or editor plugin) is\ncausing problems your the elm-stuff/ directory. Try disabling 3rd party tools\none by one until you figure out which it is!"]}
```

This makes us think that perhaps some transformers are running concurrently and stepping on each others' toes.

We are running parcel on multiple entrypoints at once via the `"source"` directive in `package.json`:
```
  "source": ["index.html", "ui-explorer.html", "redesign.html", "blobitecture/book.html" ],
```

The hypothesis is IMHO also generally supported by what we're seeing in the CI beforehand: 

```
Building...
parcel-transformer-elm-svg-modules: Writing module to: src/Shared/Svg/Icons.elm 
for assets/svg/icons/*.svg
parcel-transformer-elm-svg-modules: Writing module to: src/Shared/Svg/Icons.elm 
for assets/svg/icons/*.svg
parcel-transformer-elm-svg-modules: Writing module to: src/Shared/Svg/Icons.elm 
for assets/svg/icons/*.svg
parcel-transformer-elm-svg-modules: Generated 1 module(s)
parcel-transformer-elm-svg-modules: Generated 1 module(s)
parcel-transformer-elm-svg-modules: Generated 1 module(s)
```

ie. it's running multiple times instead of just once. Is this some property of Parcel transformers, compared to eg. bundlers or resolvers etc?

There's also the curious timing with Parcel 2.6.2 release -- the [changelog is saying something about fixing concurrent writes](https://github.com/parcel-bundler/parcel/blob/v2/CHANGELOG.md#262---2022-06-21) (upgrading didn't help, we're still seeing the issue).

All in all, I don't have a precise cause found and it's still a bit of a mystery, but it might be that the transformer is running multiple times at once, causing Elm compiler to run multiple times at once and overwriting the `i.dat` cache file, corrupting it. I'm not really sure. Just thought to log it publicly in case multiple people see a similar issue.

**Comment by Janiczek** [comment]
OTOH I've tried to disprove the hypothesis by removing the plugin altogether, and I still can reproduce the issue in our CI afterwards. So I'll close this issue here.

**Comment by ChristophP** [comment]
Oh that sounds like an annoying issue.

I also doubt that it is related to this package because this package doesn't even run the elm compiler. It only generates Elm code and writes it to disk.

On the other hand, without looking into code, I wouldn't rule out it has something to do with `@parcel/transformer-elm`. I know that parcel transformer to some parallelization and spawns a worker farm (there's some code that deals with it a bit https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/elm/src/ElmTransformer.js#L15-L21), but I haven't looked into how that works yet.
But I actually thought the Elm compiler uses some file locking mechanism to prevent that sort of thing.

**Comment by ChristophP** [comment]
Anyway, if you find some more information to reproduce it, I'll be glad to help.

**Comment by ChristophP** [comment]
I was also looking at the CLI options for parcel whether there is some flag to turn of any parallelization but I couldn't find anything about it.
